menu:
    Blog: /
    Archive: /archives/
    Tag: /tags/
    GitHub: https://github.com/maohhgg
    Rss: /atom.xml

favicon: /favicon.ico
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: maohhgg

# Analytics
# google-analytics:
ga: UA-110078780-1

# Copyright Infomation
startyear: 2015
